language: node_js
notifications:
  email: false
node_js:
  - 'lts/*'
install:
  - yarn
before_script:
  - yarn run lerna run prepublish
script:
  - yarn lerna:build-libs
after_success:
  - yarn run travis-deploy-once "yarn run lerna:release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache: yarn
deploy:
  provider: script
  script: 'yarn run lerna:publish'
  skip_cleanup: true
  on:
    tags: true
