language: node_js
notifications:
  email: false
node_js:
  - 'lts/*'
install:
  - yarn
before_script:
  - yarn run lerna run prepublish
script:
  - yarn lerna:build-libs
  - yarn lerna:version
cache:
  yarn: true
  directories:
    - 'node_modules'
deploy:
  provider: script
  script: 'yarn run lerna:publish'
  skip_cleanup: true
  on:
    tags: true
