language: node_js
notifications:
  email: false
node_js:
  - 'lts/*'
install:
  - yarn
script:
  - yarn global add lerna-semantic-release
  - yarn lerna:build-libs
after_success:
  - yarn run travis-deploy-once "yarn run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache: yarn
